name: xrandom
description: "Random number generators library focused on the consistency,
              performance and reproducibility"
version: 0.6.0
homepage: https://github.com/rtmigo/xrandom

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  quiver: ^3.0.0
  test: ^1.5.1